### ISSUE TITLE
Missing tests!

### ISSUE THREAD

**Issue by otherworldlyguardian** [learn-co-curriculum/react-rendering-lab#8] opened 2017-06-29 12:58 UTC
Missing tests for COMPONENTWILLUPDATE() and COMPONENTDIDUPDATE() sections.

**Comment by ivalentine** [comment] 2017-08-23 14:04
This is a partial duplicate of #7. Tests for both `Animation` and `Pikachu` are missing.

It looks like they were removed in 07e4d6cd30b7586a82edfce60066d0cfa1683b34. Any reason for this?

**Comment by DanielSeehausen** [comment] 2018-02-06 16:43
Hi there,

It appears this issue is either a duplicate of, or included in, an existing issue.

If you believe this issue is not already expressed in an un-closed issue on the repo, please re-open and provide further detail.

As always, thanks for contributing! 💙

(as always thank you Andrew :). Hope post Flatiron is going well!)

**Closed by DanielSeehausen** 2018-02-06 16:43 UTC
Labels: Test
